micronaut:
  application:
    name: recce
datasources:
  default:
    url: jdbc:postgresql://recce-db:5432/db
    driverClassName: org.postgresql.Driver
    username: user
    password: password
    dialect: POSTGRES
    initialization-fail-timeout: 10000
    # Only need a small pool; as only should be required for migration during startup if we continue to use R2DBC
    maximum-pool-size: 2
    minimum-idle: 1
flyway:
  datasources:
    default:
      enabled: true
r2dbc:
  datasources:
    default:
      url: r2dbc:pool:postgresql://recce-db:5432/db
      driverClassName: org.postgresql.Driver
      username: user
      password: password
      dialect: POSTGRES