r2dbc:
  datasources:
    reactive-source:
      url: r2dbc:pool:mysql://source-db:3306/db
      username: user
      password: password
      options: {}
    reactive-target:
      url: r2dbc:pool:mysql://target-db:3306/db
      username: user
      password: password
      options: {}
reconciliation:
  datasets:
    pets:
      source:
        dataSourceRef: reactive-source
        query: >
          select pet.id as MigrationKey, category, name, status
          from pet
      target:
        dataSourceRef: reactive-target
        query: >
          select pet.id as MigrationKey, category.name as category, pet.name, status
          from pet inner join category on pet.category_id = category.id
    order-status:
      source:
        dataSourceRef: reactive-source
        query: >
          select
            order_status.id as MigrationKey,
            pet_name,
            unix_timestamp(ordered_at),
            case
              when status = 1 then 'placed'
              when status = 2 then 'approved'
              when status = 3 then 'delivered'
            end as status_text,
            complete
          from order_status
      target:
        dataSourceRef: reactive-target
        query: >
          select
            order_status.id as MigrationKey,
            pet.name,
            unix_timestamp(ordered_at),
            order_status.status,
            complete
          from order_status inner join pet on order_status.pet_id = pet.id
    categories:
      source:
        dataSourceRef: reactive-source
        query: >
          select "# Categories" as MigrationKey, count(distinct category) from pet
      target :
        dataSourceRef: reactive-target
        query: >
          select "# Categories" as MigrationKey, count(*) from category
