name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**.md"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ASDF setup
        uses: asdf-vm/actions/setup@v1
      - name: ASDF Cache
        id: asdf-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.ASDF_DIR }}
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}
      - name: ASDF tool install
        uses: asdf-vm/actions/install@v1
        if: steps.asdf-cache.outputs.cache-hit != 'true'
      - name: Build with Gradle
        run: ./gradlew build
