r2dbc:
  datasources:
    source:
      url: r2dbc:pool:postgresql://source-db:5432/db
      username: user
      password: password
      options: {}
    target:
      url: r2dbc:pool:postgresql://target-db:5432/db
      username: user
      password: password
      options: {}
reconciliation:
  datasets:
    raw:
      source:
        dataSourceRef: source
        query: >
          select id as MigrationKey, *
          from big_table
      target:
        dataSourceRef: target
        query: >
          select id as MigrationKey, *
          from big_table
    counts:
      source:
        dataSourceRef: source
        query: >
          select 'Num rows' as MigrationKey, count(*) from big_table
      target :
        dataSourceRef: target
        query: >
          select 'Num rows' as MigrationKey, count(*) from big_table
